name: befriended_flutter
description: Application to help with Eating Disorder
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  cloud_firestore: ^3.1.12
  equatable: ^2.0.3
  firebase_auth: ^3.3.14
  firebase_core: ^1.14.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_services_binding: ^0.1.0
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.1
  intl: ^0.17.0
  json_annotation: ^4.4.0
  loading_indicator: ^3.0.3
  otp_text_field: ^1.1.2
  page_transition: ^2.0.5
  shared_preferences: ^2.0.13
  simple_animations: ^4.0.1

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.0
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/countrycodes.json
